// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bullet-server/physics.proto

#include "physics.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace physics {
PROTOBUF_CONSTEXPR ApplyImpulseRequest::ApplyImpulseRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.impulse_x_)*/0
  , /*decltype(_impl_.impulse_y_)*/0
  , /*decltype(_impl_.impulse_z_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ApplyImpulseRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ApplyImpulseRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ApplyImpulseRequestDefaultTypeInternal() {}
  union {
    ApplyImpulseRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ApplyImpulseRequestDefaultTypeInternal _ApplyImpulseRequest_default_instance_;
PROTOBUF_CONSTEXPR ApplyImpulseResponse::ApplyImpulseResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ApplyImpulseResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ApplyImpulseResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ApplyImpulseResponseDefaultTypeInternal() {}
  union {
    ApplyImpulseResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ApplyImpulseResponseDefaultTypeInternal _ApplyImpulseResponse_default_instance_;
PROTOBUF_CONSTEXPR GetStateRequest::GetStateRequest(
    ::_pbi::ConstantInitialized) {}
struct GetStateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetStateRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetStateRequestDefaultTypeInternal() {}
  union {
    GetStateRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetStateRequestDefaultTypeInternal _GetStateRequest_default_instance_;
PROTOBUF_CONSTEXPR GetStateResponse::GetStateResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_.qx_)*/0
  , /*decltype(_impl_.qy_)*/0
  , /*decltype(_impl_.qz_)*/0
  , /*decltype(_impl_.qw_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetStateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetStateResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetStateResponseDefaultTypeInternal() {}
  union {
    GetStateResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetStateResponseDefaultTypeInternal _GetStateResponse_default_instance_;
PROTOBUF_CONSTEXPR StepRequest::StepRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dt_)*/0
  , /*decltype(_impl_.substeps_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StepRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StepRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StepRequestDefaultTypeInternal() {}
  union {
    StepRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StepRequestDefaultTypeInternal _StepRequest_default_instance_;
PROTOBUF_CONSTEXPR StepResponse::StepResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_.qx_)*/0
  , /*decltype(_impl_.qy_)*/0
  , /*decltype(_impl_.qz_)*/0
  , /*decltype(_impl_.qw_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StepResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StepResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StepResponseDefaultTypeInternal() {}
  union {
    StepResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StepResponseDefaultTypeInternal _StepResponse_default_instance_;
}  // namespace physics
static ::_pb::Metadata file_level_metadata_bullet_2dserver_2fphysics_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_bullet_2dserver_2fphysics_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_bullet_2dserver_2fphysics_2eproto = nullptr;

const uint32_t TableStruct_bullet_2dserver_2fphysics_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::physics::ApplyImpulseRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::physics::ApplyImpulseRequest, _impl_.impulse_x_),
  PROTOBUF_FIELD_OFFSET(::physics::ApplyImpulseRequest, _impl_.impulse_y_),
  PROTOBUF_FIELD_OFFSET(::physics::ApplyImpulseRequest, _impl_.impulse_z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::physics::ApplyImpulseResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::physics::ApplyImpulseResponse, _impl_.status_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::physics::GetStateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _impl_.z_),
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _impl_.qx_),
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _impl_.qy_),
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _impl_.qz_),
  PROTOBUF_FIELD_OFFSET(::physics::GetStateResponse, _impl_.qw_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::physics::StepRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::physics::StepRequest, _impl_.dt_),
  PROTOBUF_FIELD_OFFSET(::physics::StepRequest, _impl_.substeps_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _impl_.z_),
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _impl_.qx_),
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _impl_.qy_),
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _impl_.qz_),
  PROTOBUF_FIELD_OFFSET(::physics::StepResponse, _impl_.qw_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::physics::ApplyImpulseRequest)},
  { 9, -1, -1, sizeof(::physics::ApplyImpulseResponse)},
  { 16, -1, -1, sizeof(::physics::GetStateRequest)},
  { 22, -1, -1, sizeof(::physics::GetStateResponse)},
  { 35, -1, -1, sizeof(::physics::StepRequest)},
  { 43, -1, -1, sizeof(::physics::StepResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::physics::_ApplyImpulseRequest_default_instance_._instance,
  &::physics::_ApplyImpulseResponse_default_instance_._instance,
  &::physics::_GetStateRequest_default_instance_._instance,
  &::physics::_GetStateResponse_default_instance_._instance,
  &::physics::_StepRequest_default_instance_._instance,
  &::physics::_StepResponse_default_instance_._instance,
};

const char descriptor_table_protodef_bullet_2dserver_2fphysics_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033bullet-server/physics.proto\022\007physics\"N"
  "\n\023ApplyImpulseRequest\022\021\n\timpulse_x\030\001 \001(\002"
  "\022\021\n\timpulse_y\030\002 \001(\002\022\021\n\timpulse_z\030\003 \001(\002\"&"
  "\n\024ApplyImpulseResponse\022\016\n\006status\030\001 \001(\t\"\021"
  "\n\017GetStateRequest\"c\n\020GetStateResponse\022\t\n"
  "\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022\n\n\002qx\030\004 \001"
  "(\002\022\n\n\002qy\030\005 \001(\002\022\n\n\002qz\030\006 \001(\002\022\n\n\002qw\030\007 \001(\002\"+"
  "\n\013StepRequest\022\n\n\002dt\030\001 \001(\002\022\020\n\010substeps\030\002 "
  "\001(\005\"_\n\014StepResponse\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001("
  "\002\022\t\n\001z\030\003 \001(\002\022\n\n\002qx\030\004 \001(\002\022\n\n\002qy\030\005 \001(\002\022\n\n\002"
  "qz\030\006 \001(\002\022\n\n\002qw\030\007 \001(\0022\314\001\n\007Physics\022K\n\014Appl"
  "yImpulse\022\034.physics.ApplyImpulseRequest\032\035"
  ".physics.ApplyImpulseResponse\022\?\n\010GetStat"
  "e\022\030.physics.GetStateRequest\032\031.physics.Ge"
  "tStateResponse\0223\n\004Step\022\024.physics.StepReq"
  "uest\032\025.physics.StepResponseB\037Z\035bullet-se"
  "rver/physics;physicsb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_bullet_2dserver_2fphysics_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_bullet_2dserver_2fphysics_2eproto = {
    false, false, 668, descriptor_table_protodef_bullet_2dserver_2fphysics_2eproto,
    "bullet-server/physics.proto",
    &descriptor_table_bullet_2dserver_2fphysics_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_bullet_2dserver_2fphysics_2eproto::offsets,
    file_level_metadata_bullet_2dserver_2fphysics_2eproto, file_level_enum_descriptors_bullet_2dserver_2fphysics_2eproto,
    file_level_service_descriptors_bullet_2dserver_2fphysics_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_bullet_2dserver_2fphysics_2eproto_getter() {
  return &descriptor_table_bullet_2dserver_2fphysics_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_bullet_2dserver_2fphysics_2eproto(&descriptor_table_bullet_2dserver_2fphysics_2eproto);
namespace physics {

// ===================================================================

class ApplyImpulseRequest::_Internal {
 public:
};

ApplyImpulseRequest::ApplyImpulseRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:physics.ApplyImpulseRequest)
}
ApplyImpulseRequest::ApplyImpulseRequest(const ApplyImpulseRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ApplyImpulseRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.impulse_x_){}
    , decltype(_impl_.impulse_y_){}
    , decltype(_impl_.impulse_z_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.impulse_x_, &from._impl_.impulse_x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.impulse_z_) -
    reinterpret_cast<char*>(&_impl_.impulse_x_)) + sizeof(_impl_.impulse_z_));
  // @@protoc_insertion_point(copy_constructor:physics.ApplyImpulseRequest)
}

inline void ApplyImpulseRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.impulse_x_){0}
    , decltype(_impl_.impulse_y_){0}
    , decltype(_impl_.impulse_z_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ApplyImpulseRequest::~ApplyImpulseRequest() {
  // @@protoc_insertion_point(destructor:physics.ApplyImpulseRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ApplyImpulseRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ApplyImpulseRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ApplyImpulseRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:physics.ApplyImpulseRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.impulse_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.impulse_z_) -
      reinterpret_cast<char*>(&_impl_.impulse_x_)) + sizeof(_impl_.impulse_z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ApplyImpulseRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float impulse_x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.impulse_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float impulse_y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.impulse_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float impulse_z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.impulse_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ApplyImpulseRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:physics.ApplyImpulseRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float impulse_x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_x = this->_internal_impulse_x();
  uint32_t raw_impulse_x;
  memcpy(&raw_impulse_x, &tmp_impulse_x, sizeof(tmp_impulse_x));
  if (raw_impulse_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_impulse_x(), target);
  }

  // float impulse_y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_y = this->_internal_impulse_y();
  uint32_t raw_impulse_y;
  memcpy(&raw_impulse_y, &tmp_impulse_y, sizeof(tmp_impulse_y));
  if (raw_impulse_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_impulse_y(), target);
  }

  // float impulse_z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_z = this->_internal_impulse_z();
  uint32_t raw_impulse_z;
  memcpy(&raw_impulse_z, &tmp_impulse_z, sizeof(tmp_impulse_z));
  if (raw_impulse_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_impulse_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:physics.ApplyImpulseRequest)
  return target;
}

size_t ApplyImpulseRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:physics.ApplyImpulseRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float impulse_x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_x = this->_internal_impulse_x();
  uint32_t raw_impulse_x;
  memcpy(&raw_impulse_x, &tmp_impulse_x, sizeof(tmp_impulse_x));
  if (raw_impulse_x != 0) {
    total_size += 1 + 4;
  }

  // float impulse_y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_y = this->_internal_impulse_y();
  uint32_t raw_impulse_y;
  memcpy(&raw_impulse_y, &tmp_impulse_y, sizeof(tmp_impulse_y));
  if (raw_impulse_y != 0) {
    total_size += 1 + 4;
  }

  // float impulse_z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_z = this->_internal_impulse_z();
  uint32_t raw_impulse_z;
  memcpy(&raw_impulse_z, &tmp_impulse_z, sizeof(tmp_impulse_z));
  if (raw_impulse_z != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ApplyImpulseRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ApplyImpulseRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ApplyImpulseRequest::GetClassData() const { return &_class_data_; }


void ApplyImpulseRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ApplyImpulseRequest*>(&to_msg);
  auto& from = static_cast<const ApplyImpulseRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:physics.ApplyImpulseRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_x = from._internal_impulse_x();
  uint32_t raw_impulse_x;
  memcpy(&raw_impulse_x, &tmp_impulse_x, sizeof(tmp_impulse_x));
  if (raw_impulse_x != 0) {
    _this->_internal_set_impulse_x(from._internal_impulse_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_y = from._internal_impulse_y();
  uint32_t raw_impulse_y;
  memcpy(&raw_impulse_y, &tmp_impulse_y, sizeof(tmp_impulse_y));
  if (raw_impulse_y != 0) {
    _this->_internal_set_impulse_y(from._internal_impulse_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_impulse_z = from._internal_impulse_z();
  uint32_t raw_impulse_z;
  memcpy(&raw_impulse_z, &tmp_impulse_z, sizeof(tmp_impulse_z));
  if (raw_impulse_z != 0) {
    _this->_internal_set_impulse_z(from._internal_impulse_z());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ApplyImpulseRequest::CopyFrom(const ApplyImpulseRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:physics.ApplyImpulseRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ApplyImpulseRequest::IsInitialized() const {
  return true;
}

void ApplyImpulseRequest::InternalSwap(ApplyImpulseRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ApplyImpulseRequest, _impl_.impulse_z_)
      + sizeof(ApplyImpulseRequest::_impl_.impulse_z_)
      - PROTOBUF_FIELD_OFFSET(ApplyImpulseRequest, _impl_.impulse_x_)>(
          reinterpret_cast<char*>(&_impl_.impulse_x_),
          reinterpret_cast<char*>(&other->_impl_.impulse_x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ApplyImpulseRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bullet_2dserver_2fphysics_2eproto_getter, &descriptor_table_bullet_2dserver_2fphysics_2eproto_once,
      file_level_metadata_bullet_2dserver_2fphysics_2eproto[0]);
}

// ===================================================================

class ApplyImpulseResponse::_Internal {
 public:
};

ApplyImpulseResponse::ApplyImpulseResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:physics.ApplyImpulseResponse)
}
ApplyImpulseResponse::ApplyImpulseResponse(const ApplyImpulseResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ApplyImpulseResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_status().empty()) {
    _this->_impl_.status_.Set(from._internal_status(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:physics.ApplyImpulseResponse)
}

inline void ApplyImpulseResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ApplyImpulseResponse::~ApplyImpulseResponse() {
  // @@protoc_insertion_point(destructor:physics.ApplyImpulseResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ApplyImpulseResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.status_.Destroy();
}

void ApplyImpulseResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ApplyImpulseResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:physics.ApplyImpulseResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ApplyImpulseResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_status();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "physics.ApplyImpulseResponse.status"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ApplyImpulseResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:physics.ApplyImpulseResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_status().data(), static_cast<int>(this->_internal_status().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "physics.ApplyImpulseResponse.status");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:physics.ApplyImpulseResponse)
  return target;
}

size_t ApplyImpulseResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:physics.ApplyImpulseResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ApplyImpulseResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ApplyImpulseResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ApplyImpulseResponse::GetClassData() const { return &_class_data_; }


void ApplyImpulseResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ApplyImpulseResponse*>(&to_msg);
  auto& from = static_cast<const ApplyImpulseResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:physics.ApplyImpulseResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ApplyImpulseResponse::CopyFrom(const ApplyImpulseResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:physics.ApplyImpulseResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ApplyImpulseResponse::IsInitialized() const {
  return true;
}

void ApplyImpulseResponse::InternalSwap(ApplyImpulseResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.status_, lhs_arena,
      &other->_impl_.status_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ApplyImpulseResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bullet_2dserver_2fphysics_2eproto_getter, &descriptor_table_bullet_2dserver_2fphysics_2eproto_once,
      file_level_metadata_bullet_2dserver_2fphysics_2eproto[1]);
}

// ===================================================================

class GetStateRequest::_Internal {
 public:
};

GetStateRequest::GetStateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:physics.GetStateRequest)
}
GetStateRequest::GetStateRequest(const GetStateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  GetStateRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:physics.GetStateRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetStateRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetStateRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata GetStateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bullet_2dserver_2fphysics_2eproto_getter, &descriptor_table_bullet_2dserver_2fphysics_2eproto_once,
      file_level_metadata_bullet_2dserver_2fphysics_2eproto[2]);
}

// ===================================================================

class GetStateResponse::_Internal {
 public:
};

GetStateResponse::GetStateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:physics.GetStateResponse)
}
GetStateResponse::GetStateResponse(const GetStateResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetStateResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , decltype(_impl_.qx_){}
    , decltype(_impl_.qy_){}
    , decltype(_impl_.qz_){}
    , decltype(_impl_.qw_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.qw_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.qw_));
  // @@protoc_insertion_point(copy_constructor:physics.GetStateResponse)
}

inline void GetStateResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , decltype(_impl_.qx_){0}
    , decltype(_impl_.qy_){0}
    , decltype(_impl_.qz_){0}
    , decltype(_impl_.qw_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetStateResponse::~GetStateResponse() {
  // @@protoc_insertion_point(destructor:physics.GetStateResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetStateResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetStateResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetStateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:physics.GetStateResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.qw_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.qw_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetStateResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qx = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.qx_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qy = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.qy_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qz = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.qz_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qw = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.qw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetStateResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:physics.GetStateResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_z(), target);
  }

  // float qx = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qx = this->_internal_qx();
  uint32_t raw_qx;
  memcpy(&raw_qx, &tmp_qx, sizeof(tmp_qx));
  if (raw_qx != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_qx(), target);
  }

  // float qy = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qy = this->_internal_qy();
  uint32_t raw_qy;
  memcpy(&raw_qy, &tmp_qy, sizeof(tmp_qy));
  if (raw_qy != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_qy(), target);
  }

  // float qz = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qz = this->_internal_qz();
  uint32_t raw_qz;
  memcpy(&raw_qz, &tmp_qz, sizeof(tmp_qz));
  if (raw_qz != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_qz(), target);
  }

  // float qw = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qw = this->_internal_qw();
  uint32_t raw_qw;
  memcpy(&raw_qw, &tmp_qw, sizeof(tmp_qw));
  if (raw_qw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_qw(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:physics.GetStateResponse)
  return target;
}

size_t GetStateResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:physics.GetStateResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 4;
  }

  // float qx = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qx = this->_internal_qx();
  uint32_t raw_qx;
  memcpy(&raw_qx, &tmp_qx, sizeof(tmp_qx));
  if (raw_qx != 0) {
    total_size += 1 + 4;
  }

  // float qy = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qy = this->_internal_qy();
  uint32_t raw_qy;
  memcpy(&raw_qy, &tmp_qy, sizeof(tmp_qy));
  if (raw_qy != 0) {
    total_size += 1 + 4;
  }

  // float qz = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qz = this->_internal_qz();
  uint32_t raw_qz;
  memcpy(&raw_qz, &tmp_qz, sizeof(tmp_qz));
  if (raw_qz != 0) {
    total_size += 1 + 4;
  }

  // float qw = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qw = this->_internal_qw();
  uint32_t raw_qw;
  memcpy(&raw_qw, &tmp_qw, sizeof(tmp_qw));
  if (raw_qw != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetStateResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetStateResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetStateResponse::GetClassData() const { return &_class_data_; }


void GetStateResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetStateResponse*>(&to_msg);
  auto& from = static_cast<const GetStateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:physics.GetStateResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qx = from._internal_qx();
  uint32_t raw_qx;
  memcpy(&raw_qx, &tmp_qx, sizeof(tmp_qx));
  if (raw_qx != 0) {
    _this->_internal_set_qx(from._internal_qx());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qy = from._internal_qy();
  uint32_t raw_qy;
  memcpy(&raw_qy, &tmp_qy, sizeof(tmp_qy));
  if (raw_qy != 0) {
    _this->_internal_set_qy(from._internal_qy());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qz = from._internal_qz();
  uint32_t raw_qz;
  memcpy(&raw_qz, &tmp_qz, sizeof(tmp_qz));
  if (raw_qz != 0) {
    _this->_internal_set_qz(from._internal_qz());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qw = from._internal_qw();
  uint32_t raw_qw;
  memcpy(&raw_qw, &tmp_qw, sizeof(tmp_qw));
  if (raw_qw != 0) {
    _this->_internal_set_qw(from._internal_qw());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetStateResponse::CopyFrom(const GetStateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:physics.GetStateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetStateResponse::IsInitialized() const {
  return true;
}

void GetStateResponse::InternalSwap(GetStateResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetStateResponse, _impl_.qw_)
      + sizeof(GetStateResponse::_impl_.qw_)
      - PROTOBUF_FIELD_OFFSET(GetStateResponse, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetStateResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bullet_2dserver_2fphysics_2eproto_getter, &descriptor_table_bullet_2dserver_2fphysics_2eproto_once,
      file_level_metadata_bullet_2dserver_2fphysics_2eproto[3]);
}

// ===================================================================

class StepRequest::_Internal {
 public:
};

StepRequest::StepRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:physics.StepRequest)
}
StepRequest::StepRequest(const StepRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StepRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.dt_){}
    , decltype(_impl_.substeps_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.dt_, &from._impl_.dt_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.substeps_) -
    reinterpret_cast<char*>(&_impl_.dt_)) + sizeof(_impl_.substeps_));
  // @@protoc_insertion_point(copy_constructor:physics.StepRequest)
}

inline void StepRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.dt_){0}
    , decltype(_impl_.substeps_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StepRequest::~StepRequest() {
  // @@protoc_insertion_point(destructor:physics.StepRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StepRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void StepRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StepRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:physics.StepRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dt_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.substeps_) -
      reinterpret_cast<char*>(&_impl_.dt_)) + sizeof(_impl_.substeps_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StepRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float dt = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.dt_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 substeps = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.substeps_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StepRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:physics.StepRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float dt = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_dt = this->_internal_dt();
  uint32_t raw_dt;
  memcpy(&raw_dt, &tmp_dt, sizeof(tmp_dt));
  if (raw_dt != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_dt(), target);
  }

  // int32 substeps = 2;
  if (this->_internal_substeps() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_substeps(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:physics.StepRequest)
  return target;
}

size_t StepRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:physics.StepRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float dt = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_dt = this->_internal_dt();
  uint32_t raw_dt;
  memcpy(&raw_dt, &tmp_dt, sizeof(tmp_dt));
  if (raw_dt != 0) {
    total_size += 1 + 4;
  }

  // int32 substeps = 2;
  if (this->_internal_substeps() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_substeps());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StepRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StepRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StepRequest::GetClassData() const { return &_class_data_; }


void StepRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StepRequest*>(&to_msg);
  auto& from = static_cast<const StepRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:physics.StepRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_dt = from._internal_dt();
  uint32_t raw_dt;
  memcpy(&raw_dt, &tmp_dt, sizeof(tmp_dt));
  if (raw_dt != 0) {
    _this->_internal_set_dt(from._internal_dt());
  }
  if (from._internal_substeps() != 0) {
    _this->_internal_set_substeps(from._internal_substeps());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StepRequest::CopyFrom(const StepRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:physics.StepRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StepRequest::IsInitialized() const {
  return true;
}

void StepRequest::InternalSwap(StepRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StepRequest, _impl_.substeps_)
      + sizeof(StepRequest::_impl_.substeps_)
      - PROTOBUF_FIELD_OFFSET(StepRequest, _impl_.dt_)>(
          reinterpret_cast<char*>(&_impl_.dt_),
          reinterpret_cast<char*>(&other->_impl_.dt_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StepRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bullet_2dserver_2fphysics_2eproto_getter, &descriptor_table_bullet_2dserver_2fphysics_2eproto_once,
      file_level_metadata_bullet_2dserver_2fphysics_2eproto[4]);
}

// ===================================================================

class StepResponse::_Internal {
 public:
};

StepResponse::StepResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:physics.StepResponse)
}
StepResponse::StepResponse(const StepResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StepResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , decltype(_impl_.qx_){}
    , decltype(_impl_.qy_){}
    , decltype(_impl_.qz_){}
    , decltype(_impl_.qw_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.qw_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.qw_));
  // @@protoc_insertion_point(copy_constructor:physics.StepResponse)
}

inline void StepResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , decltype(_impl_.qx_){0}
    , decltype(_impl_.qy_){0}
    , decltype(_impl_.qz_){0}
    , decltype(_impl_.qw_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StepResponse::~StepResponse() {
  // @@protoc_insertion_point(destructor:physics.StepResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StepResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void StepResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StepResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:physics.StepResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.qw_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.qw_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StepResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qx = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.qx_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qy = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.qy_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qz = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.qz_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float qw = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.qw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StepResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:physics.StepResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_z(), target);
  }

  // float qx = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qx = this->_internal_qx();
  uint32_t raw_qx;
  memcpy(&raw_qx, &tmp_qx, sizeof(tmp_qx));
  if (raw_qx != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_qx(), target);
  }

  // float qy = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qy = this->_internal_qy();
  uint32_t raw_qy;
  memcpy(&raw_qy, &tmp_qy, sizeof(tmp_qy));
  if (raw_qy != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_qy(), target);
  }

  // float qz = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qz = this->_internal_qz();
  uint32_t raw_qz;
  memcpy(&raw_qz, &tmp_qz, sizeof(tmp_qz));
  if (raw_qz != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_qz(), target);
  }

  // float qw = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qw = this->_internal_qw();
  uint32_t raw_qw;
  memcpy(&raw_qw, &tmp_qw, sizeof(tmp_qw));
  if (raw_qw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_qw(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:physics.StepResponse)
  return target;
}

size_t StepResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:physics.StepResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 4;
  }

  // float qx = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qx = this->_internal_qx();
  uint32_t raw_qx;
  memcpy(&raw_qx, &tmp_qx, sizeof(tmp_qx));
  if (raw_qx != 0) {
    total_size += 1 + 4;
  }

  // float qy = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qy = this->_internal_qy();
  uint32_t raw_qy;
  memcpy(&raw_qy, &tmp_qy, sizeof(tmp_qy));
  if (raw_qy != 0) {
    total_size += 1 + 4;
  }

  // float qz = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qz = this->_internal_qz();
  uint32_t raw_qz;
  memcpy(&raw_qz, &tmp_qz, sizeof(tmp_qz));
  if (raw_qz != 0) {
    total_size += 1 + 4;
  }

  // float qw = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qw = this->_internal_qw();
  uint32_t raw_qw;
  memcpy(&raw_qw, &tmp_qw, sizeof(tmp_qw));
  if (raw_qw != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StepResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StepResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StepResponse::GetClassData() const { return &_class_data_; }


void StepResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StepResponse*>(&to_msg);
  auto& from = static_cast<const StepResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:physics.StepResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qx = from._internal_qx();
  uint32_t raw_qx;
  memcpy(&raw_qx, &tmp_qx, sizeof(tmp_qx));
  if (raw_qx != 0) {
    _this->_internal_set_qx(from._internal_qx());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qy = from._internal_qy();
  uint32_t raw_qy;
  memcpy(&raw_qy, &tmp_qy, sizeof(tmp_qy));
  if (raw_qy != 0) {
    _this->_internal_set_qy(from._internal_qy());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qz = from._internal_qz();
  uint32_t raw_qz;
  memcpy(&raw_qz, &tmp_qz, sizeof(tmp_qz));
  if (raw_qz != 0) {
    _this->_internal_set_qz(from._internal_qz());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_qw = from._internal_qw();
  uint32_t raw_qw;
  memcpy(&raw_qw, &tmp_qw, sizeof(tmp_qw));
  if (raw_qw != 0) {
    _this->_internal_set_qw(from._internal_qw());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StepResponse::CopyFrom(const StepResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:physics.StepResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StepResponse::IsInitialized() const {
  return true;
}

void StepResponse::InternalSwap(StepResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StepResponse, _impl_.qw_)
      + sizeof(StepResponse::_impl_.qw_)
      - PROTOBUF_FIELD_OFFSET(StepResponse, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StepResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_bullet_2dserver_2fphysics_2eproto_getter, &descriptor_table_bullet_2dserver_2fphysics_2eproto_once,
      file_level_metadata_bullet_2dserver_2fphysics_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace physics
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::physics::ApplyImpulseRequest*
Arena::CreateMaybeMessage< ::physics::ApplyImpulseRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::physics::ApplyImpulseRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::physics::ApplyImpulseResponse*
Arena::CreateMaybeMessage< ::physics::ApplyImpulseResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::physics::ApplyImpulseResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::physics::GetStateRequest*
Arena::CreateMaybeMessage< ::physics::GetStateRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::physics::GetStateRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::physics::GetStateResponse*
Arena::CreateMaybeMessage< ::physics::GetStateResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::physics::GetStateResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::physics::StepRequest*
Arena::CreateMaybeMessage< ::physics::StepRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::physics::StepRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::physics::StepResponse*
Arena::CreateMaybeMessage< ::physics::StepResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::physics::StepResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
